### ISSUE TITLE
Steps for Setup?

### ISSUE THREAD

**Issue by al3x1337** [martynvdijke/SoundBridgeFx#1]
Very interested in trying to get this project running, if it is functional. It seems the kasm branch is the most active, I'm wondering if some simple steps can be posted on how to get this working? 

Currently using WSL2 + Docker Desktop (Windows) to get it running with Docker Compose. The furthest I got was a basic auth pop up asking for creds, no matter what is entered a blank screen proceeds it.

`2023-10-27 10:54:12  2023-10-27 14:54:12,183 [INFO] websocket 5: got client connection from 172.17.0.1
2023-10-27 10:54:12  2023-10-27 14:54:12,189 [DEBUG] websocket 5: using SSL socket
2023-10-27 10:54:12  2023-10-27 14:54:12,189 [INFO] websocket 5: Authentication attempt failed, BasicAuth required, but client didn't send any`

`soundbridge  |  2023-10-27 20:28:28,361 [DEBUG] websocket 36: using SSL socket
soundbridge  |  2023-10-27 20:28:28,361 [INFO] websocket 36: IP 172.18.0.1 is blacklisted, dropping
soundbridge  |  2023-10-27 20:28:28,361 [INFO] websocket 36: 172.18.0.1 172.18.0.1 - "GET / HTTP/1.1" 401 26
soundbridge  |  2023-10-27 20:28:28,361 [DEBUG] websocket 36: No connection after handshake
soundbridge  |  2023-10-27 20:28:28,361 [DEBUG] websocket 36: handler exit`

Additional documnetation on how to get this running/the credentials would be appreciated! 

Thank you!

**Comment by martynvdijke** [comment]
Yeah my initial route was not really working out the way I intended it to do, I swichted to a custom image.
You should be able to add this custom image in kasm as `martynvandijke/soundbridgefx:latest` 
Hope that helps ?
